### ISSUE TITLE
Windows version crashes opening a file

### ISSUE THREAD

**Issue by wheineman** [vamolessa/pepper#9] opened 2021-05-28 09:33 UTC
Cargo built version v0.10.6 crashes when opening a file, either from the command line or with the open command:
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', C:\Users\whein\.cargo\registry\src\github.com-1ecc6299db9ec823\pepper-0.10.6\src\buffer.rs:364:10

**Comment by vamolessa** [comment] 2021-05-28 13:50
What were the file contents?
You can reproduce it just by invoking `pepper filename.ext` with default configs?
Does this happen with any file or just one specifically?
Did you built from source? If so, could you try building from master's current HEAD `b1657c5`?

**Comment by wheineman** [comment] 2021-05-28 15:58
Hi,    
It happens with any text file. 
I created a text file call test.txt with one line in it and it failed to load. It failed when I invoked "pepper test.txt" with default configs (I have not created any config file).I built and installed pepper using cargo, i.e. "cargo install pepper".I will try building from the HEAD and let you know the results.
Cheers,
Willy 

    On Friday, May 28, 2021, 9:51:19 AM EDT, Matheus Lessa Rodrigues ***@***.***> wrote:  
 
 


What were the file contents?
You can reproduce it just by invoking pepper filename.ext with default configs?
Does this happen with any file or just one specifically?
Did you built from source? If so, could you try building from master's current HEAD b1657c5?

**Comment by vamolessa** [comment] 2021-05-29 15:40
Did it work using a newer commit? I really could not reproduce your issue.
I develop it on windows and use pepper as my main editor but this crash never happened to me.
If you have any further clue, please let me know

**Comment by wheineman** [comment] 2021-05-29 19:27
Hi,    I cloned the github repository and built both the debug and release versions of Pepper and they both read files fine, whether from the command line at startup or with the open command. So that's great. I don't know why the one built with the "cargo install pepper" command failed but maybe that should be pointed out for Windows users.
Cheers,
Willy
    On Saturday, May 29, 2021, 11:40:30 AM EDT, Matheus Lessa Rodrigues ***@***.***> wrote:  
 
 


Did it work using a newer commit? I really could not reproduce your issue.
I develop it on windows and use pepper as my main editor but this crash never happened to me.
If you have any further clue, please let me know

**Comment by wheineman** [comment] 2021-05-29 19:29
Also thanks for pepper. I'm enjoying it immensely.
Cheers,
Willy

    On Saturday, May 29, 2021, 3:27:34 PM EDT, William Heineman ***@***.***> wrote:  
 
  Hi,    I cloned the github repository and built both the debug and release versions of Pepper and they both read files fine, whether from the command line at startup or with the open command. So that's great. I don't know why the one built with the "cargo install pepper" command failed but maybe that should be pointed out for Windows users.
Cheers,
Willy
    On Saturday, May 29, 2021, 11:40:30 AM EDT, Matheus Lessa Rodrigues ***@***.***> wrote:  
 
 


Did it work using a newer commit? I really could not reproduce your issue.
I develop it on windows and use pepper as my main editor but this crash never happened to me.
If you have any further clue, please let me know

**Comment by vamolessa** [comment] 2021-05-29 21:09
Ah, that's good to hear! Thanks for following up!
Gonna close this then

**Closed by vamolessa** 2021-05-29 21:09 UTC
